### ISSUE TITLE
Visualizer breaks

### ISSUE THREAD

**Issue by eznix86** [yandeu/docker-swarm-visualizer#15]
I wanted to try out 3 managers on a cluster of 3 nodes. I kill one node to the see the behaviour, the visualizer broke and show only one node.

After killing one node:

<img width="784" alt="Screenshot 2024-06-28 at 01 03 20" src="https://github.com/yandeu/docker-swarm-visualizer/assets/26553194/737c2d43-587b-4991-aa26-7ca428f7508d">

Using 3 VM (Ubuntu mutlpass)

<img width="588" alt="Screenshot 2024-06-28 at 01 10 53" src="https://github.com/yandeu/docker-swarm-visualizer/assets/26553194/3bee92eb-a0be-4d75-abea-6fb382aed4da">

This is what I get:

<img width="927" alt="Screenshot 2024-06-28 at 00 59 52" src="https://github.com/yandeu/docker-swarm-visualizer/assets/26553194/0425433f-f96a-4ca9-b45f-9d77cabf8a23">

The configuration (taken from the docs)

```yaml
version: '3.9'

services:
  manager:
    environment:
      - VISUALIZER_TYPE=manager
    image: yandeu/visualizer:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    labels:
      - visualizer.manager
    healthcheck:
      test: curl -f http://localhost:3500/healthcheck || exit 1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s
    ports:
      - '9500:3500'

  agent:
    environment:
      - VISUALIZER_TYPE=agent
    image: yandeu/visualizer:dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    labels:
      - visualizer.agent
    healthcheck:
      test: curl -f http://localhost:9501/healthcheck || exit 1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

networks:
  agent_network:
    driver: overlay
    attachable: true

```
